name: Bug report
description: Report errors or unexpected behavior.
labels: [Bug]

body:
  - type: checkboxes
    attributes:
       label: Please check before submitting an issue
       options:
          - label: I have searched the issues and haven't found anything relevant
            required: true

          - label: If patch failed, root failed, or device unable to boot after flashing the new boot.img. Please goto KernelPatch
            required: true

          - label: I will upload bugreport file in APatch Manager - Settings - Report log
            required: true

          - label: My problem is fully stated in English. 
            required: true

          - label: I know how to reproduce the issue which may not be specific to my device
            required: false

  - type: textarea
    attributes:
        label: Describe the bug
        description: A clear and concise description of what the bug is
    validations:
        required: true

  - type: textarea
    attributes:
        label: Reproduce method
        description: Steps to reproduce the behaviour
        placeholder: |
          - 1. Go to '...'
          - 2. Click on '....'
          - 3. Scroll down to '....'
          - 4. See error
    validations:
      required: true

  - type: textarea
    attributes:
        label: Expected behavior
        description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    attributes:
        label: Actual behaviour
        placeholder: Tell us what happens instead
    validations:
      required: true

  - type: textarea
    attributes:
        label: Screenshots
        description: If applicable, add screenshots to help explain your problem.

  - type: textarea
    attributes:
        label: Logs
        description: If applicable, add crash or any other logs to help us figure out the problem.

  - type: input
    attributes:
      label: Device Name
    validations:
      required: true

  - type: input
    attributes:
      label: OS Version
    validations:
      required: true

  - type: input
    attributes:
      label: APatch Version
    validations:
      required: true

  - type: input
    attributes:
      label: Kernel Version
    validations:
      required: true

  - type: input
    attributes:
      label: KernelPatch Version
    validations:
      required: true

  - type: textarea
    attributes:
        label: Additional context
        description: Add any other context about the problem here.
        placeholder: Upload logs zip by clicking the bar on the bottom. Upload logs to other websites or using external links is prohibited.
    validations:
      required: true
