name: Build apd
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      use_cache:
        required: false
        type: boolean
        default: true
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # cross build failed after Rust 1.68, see https://github.com/cross-rs/cross/issues/1222
      - run: rustup default 1.67.0
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: apd
          cache-targets: false

      - name: Install cross
        run: cargo install cross --locked

      - name: Build apd
        run: cross build --target aarch64-linux-android --release --manifest-path ./apd/Cargo.toml

      - name: Upload apd artifact
        uses: actions/upload-artifact@v3
        with:
          name: apd-aarch64-linux-android
          path: apd/target/**/release/apd